name: Hyphen
favicon: null
layout_spectrum: 0.8160132165066898
typography_spectrum: 0.8156053831335157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f7f7f'
    - '#004275'
    - '#0d0d0d'
    - '#7e1279'
  brandStrength: 0.44803749001584947
  lightness: 0.17939982539974153
  saturation: 0.661685150116682
  rhythmicContrast: 0.1781444197986275
purpose: []
